export interface MoviesModel {
  id: number;
  title: string;
  release_date: string;
  box_office: number;
  duration: number;
  overview: string;
  cover_url: string;
  trailer_url: string;
  directed_by: string;
  phase: number;
  saga: string;
  chronology: number;
  post_credit_scenes: number;
  imdb_id: string;
}

export interface MovieDAO {
  data: MoviesModel[];
  results: ComicsModel[];
}

export interface ComicsModel {
  id: number;
  digitalId: number;
  title: string;
  issueNumber: number;
  variantDescription: string;
  description: string;
  modified: string;
  isbn: string;
  upc: string;
  diamondCode: string;
  ean: string;
  issn: string;
  format: string;
  pageCount: number;
  //   textObjects:
  //     [{
  //       type:string;
  //       language:string;
  //       text:string}];
  //       resourceURI:string;
  //       urls:
  //       [{
  //         type:string;
  //         url:string}];
  //         series:
  //         {resourceURI:string
  //           name:string};
  //           variants:[];
  //           collections:[];
  //           collectedIssues:
  //           [{resourceURI:string;
  //             name:string},
  //             {resourceURI:string,
  //               name:string},
  //               {resourceURI:string;
  //                 name:string},
  //                 dates:
  //                 [{type:string;
  //                   date:string},
  //                   {type:string,date:string}],
  //                   prices:[{
  //                     type:string;
  //                     price:number}],
  //                   thumbnail:{path:string;
  //                     extension:string},
  //                     images:[{
  //                       path:string;
  //                       extension:string},
  //                       {path:string;
  //                         extension:string},
  //                         {path:string},
  //                         {path:string},
  //                         {path:string},
  //                         {path:string},
  //                         {path:string},
  //                         {path:string}],
  //                         creators:{
  //                           available:number;
  //                           collectionURI:string;
  //                           items:[{
  //                             resourceURI:string;
  //                             name:string;
  //                             role:string},
  //                             {resourceURI:string;
  //                               name:string,
  //                               role:string},
  //                               {resourceURI:string,
  //                                 name:string},
  //                                 {resourceURI:string;
  //                                 returned:number},
  //                                 characters:{
  //                                   available:number,
  //                                 collectionURI:string,
  //                                 items:[{
  //                                   resourceURI:string;
  //                                   )}],
  //                                   returned:number},
  //                                 stories:{available:number,
  //                                   collectionURI:number,
  //                                   items:[{
  //                                     resourceURI:string,
  //                                     name:string},
  //                                     {resourceURI:string,
  //                                       name:string,
  //                                       type:string},
  //                                       {resourceURI:string;
  //                                         name:string},
  //                                       {resourceURI:string,
  //                                         name:string;
  //                                         type:string},
  //                                       {resourceURI:string;
  //                                         name:string,
  //                                         type:string}];
  //                                         returned:number},
  //                                   events:{
  //                                     available:number;
  //                                     collectionURI:string;
  //                                     items:[];
  //                                     returned:number}]}]
}
